### ISSUE TITLE
Bottleneck distance

### ISSUE THREAD

**Issue by outlace** [ctralie/ripser#37]
How can I compute the bottleneck distance between persistence diagrams from Ripser? I was previously using the R TDA package which has this built in. Is there an alternative in Python?

**Comment by ctralie** [comment]
Thanks for your interest in our ripser wrapper! I have wanted to add this feature for some time, though it is not available officially in the master branch.  For now, I've added a branch that includes some unofficial code I wrote to do this.  There are directions in the README for how to use it:

https://github.com/ctralie/ripser/tree/bottleneck

It's not fast, but neither is the version in the R TDA package.  Eventually, I would like to create a pure python implementation similar to Hera, which is state of the art
https://bitbucket.org/grey_narn/hera
So I will keep this issue open until I do so.  But hopefully that branch is enough to keep you going in the mean time.
Best,
Chris Tralie

**Comment by ctralie** [comment]
Btw, if you run the file "DGMTools.py" in that branch, you should get an output similar to this (which will let you know the tools have installed properly):

![bottleneckexample](https://user-images.githubusercontent.com/1270246/42336725-8b4fdf4c-8052-11e8-8993-3f96035d964a.png)

**Comment by outlace** [comment]
Thanks I’ll give it a try!

**Comment by outlace** [comment]
@ctralie I just tried the bottleneck distance on the PDs of some real neuroscience data I have and it gives me very different results than using Euclidian metric on persistence images generated from the same PDs. The bottleneck function also doesn't seem to work for Betti 0 PDs. 

As an aside, if I want to compare persistence images, is the Euclidian metric a reasonable choice? I couldn't tell from the original PI paper what the natural choice would be.

**Comment by ctralie** [comment]
Okay, if you pull on that branch now the bottleneck distance should work on 0D PDs.  My guess is it was crashing with points that have infinite death times, and there is always at least one of them with 0D.  I just ignore them in the code now.  Let me know if that doesn't fix it.

As far as bottleneck versus persistence images go, I'm not surprised at all.  Bottleneck is only sensitive to the most different points in the persistence diagrams, whereas persistence images pick up on all of the points to some degree.  This is analogous to the difference between bottleneck and Wasserstein.  And this is why, in practice, even though bottleneck has better theoretical properties, I often opt for Wasserstein or other comparisons that take into consideration all of the points, not just the bottleneck.

And yes, Euclidean distance between persistence images seems reasonable.  Though there are myriad ways to compare images, I think that's a good place to start (and I honestly haven't gone beyond that yet myself in any application).

Hope that helps!
-Chris

**Comment by ctralie** [comment]
This is beyond the scope of ripser right now, moving to different project
