### ISSUE TITLE
Add support for sparse distance matrices

### ISSUE THREAD

**Issue by ctralie** [ctralie/ripser#9]
Need to merge in the branch from here:
https://github.com/Ripser/ripser/tree/sparse-distance-matrix
It would be nice to integrate inputs from scipy.sparse

This will be particularly important when doing Cech complexes on a large number of points, where most of the higher simplices are not used.

**Comment by ctralie** [comment]
I would like to see if it's possible to call scipy's sparse matrix library from within C++

**Comment by rannbaron** [comment]
Yes, though you'd probably be better off using the C++ code that
underlies SciPy's sparse matrix representations:

https://github.com/scipy/scipy/tree/master/scipy/sparse/sparsetools

**Comment by ctralie** [comment]
Ooooh nice thanks!

**Comment by ctralie** [comment]
Actually a simple approach may do.  Looks like someone has already tried this:

https://github.com/Ripser/ripser/pull/6/commits/4c17605589ca6294a6efb7eb7db64d81fea12a3d
